# Chapter 7 code blocks

In [16]:
import numpy as np
import scipy as sp
import sklearn as skl

np.random.seed(42)

### 7.3. Principal Component Analysis

**Single Value Decomposition (SVD) and Eigenvalue Decomposition (EVD)**

Checking that the diagonal matrix of eigenvalues $C_Y$ is equivalent to the square of the singular values ($\Sigma^2 = C_Y$), and the principal components can be computed from the SVD of $X$ without constructing $C_X$ (page 288).

In [ ]:
X = np.random.random((100, 3))      # Initial dataset with 100 observations made up of 3 features each
CX = np.dot(X.T, X)                 # Covariance matrix of X

U, Sdiag, VT = np.linalg.svd(X, full_matrices=False)
        # U: left-singular vectors, VT: right-singular vectors, Sdiag: diagonal of singular values matrix
CYdiag, R = np.linalg.eigh(CX)
        # CYdiag: diagonal of the sqaure of the singular values, R: principal components

In [ ]:
np.allclose(CYdiag, Sdiag[::-1]**2)     # Reverse Sdiag array

True

In [6]:
VT[::-1].T / R

array([[ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.]])

$C_Y$ and $\Sigma^2$ are equivalent; the right-hand vectors of $X$ (VT) and the eigenvectors of $C_X$ (R) are equivalent, disreguarding the signs.

Using SciPy instead gives the same results:

In [15]:
U, Sdiag, VT = sp.linalg.svd(X, full_matrices=False)
CYdiag, R = sp.linalg.eigh(CX)

np.allclose(CYdiag, Sdiag[::-1]**2)     # Reverse Sdiag array

True

In [14]:
VT[::-1].T / R

array([[-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.]])

**Application of Principal Component Analysis**

Performing PCA using Skikit-learn (page 289).

In [80]:
X = np.random.normal(size=(100, 3))
R = np.random.random((3, 10))       # Projection matrix
X = np.dot(X, R)                    # Projecting X to 10D
X.shape

(100, 10)

In [ ]:
pca = skl.decomposition.PCA(n_components=4)
comp = pca.fit_transform(X)             # Compute subspace projection of X to 4D
comp.shape

(100, 4)

*Mean* returns the mean value for each of the 10 features, to be used to centre the data vectors before analysis.

*Components* returns the eigenvectors of the prinical components (here there are 4 with 10 features each).

*Variance* returns the eigenvalues of the principal components (again 4, and the 4th is basically 0 because X originally had 3 dimensions).

In [82]:
mean = pca.mean_
components = pca.components_
var = pca.explained_variance_

print(f'Mean: {mean} \nComponents: {components} \nVariance: {var}')

Mean: [ 0.04149865 -0.01125193  0.02310002 -0.0016804   0.00909718  0.04602849
  0.02647056 -0.04674155  0.0725381   0.0692931 ] 
Components: [[ 0.38531322  0.35263947  0.36736558  0.19947342  0.4536085   0.26061738
   0.09478258  0.32992357  0.17237714  0.36221919]
 [ 0.60814084 -0.24724921 -0.01014608 -0.02328683  0.04185843 -0.35478212
  -0.0295054  -0.40053559  0.52547902 -0.05776955]
 [-0.21167054 -0.17186128  0.01362918 -0.1252777  -0.21536582  0.53545835
   0.22888612 -0.41827035  0.28825121  0.51599733]
 [ 0.46729082 -0.26317236 -0.44747884 -0.00921277 -0.11532917  0.55565869
   0.13381749  0.28475083 -0.0962054  -0.28592723]] 
Variance: [7.70664451e+00 8.18408786e-01 4.32390377e-01 6.61147697e-16]


### 7.4. Nonnegative Matrix Factorisation

**NMF**

Implementing NMF with Scikit-learn (page 297).

In [98]:
X = np.random.random((100, 3))      # 100 points in 3D, all positive

nmf = skl.decomposition.NMF(n_components=3)
proj = nmf.fit_transform(X)         # Projecting to 3D
proj.shape

(100, 3)

*Components* will return the components (here there are 3).

*Reconstruction error* shows how well the components capture the original data.

In [99]:
comp = nmf.components_
err = nmf.reconstruction_err_

print(f'Components: {comp} \nError: {err}')

Components: [[0.         0.04361279 3.40242076]
 [0.07517872 2.43286451 0.        ]
 [1.92961643 0.         0.05668228]] 
Error: 0.007608657435412712


### 7.5. Manifold Learning

**Locally Linear Embedding**

Performing LLE with Scikit-learn (page 300).

In [100]:
X = np.random.normal(size=(1000, 2))
R = np.random.random((2, 10))
X = np.dot(X, R)                # Now a 2D linear manifold in 10D space
X.shape

(1000, 10)

Using $LocallyLinearEmbedding$ to reconstruct the original 2D data, as in the book:

In [ ]:
lle = skl.manifold.LocallyLinearEmbedding(n_neighbors=5, n_components=2)
proj = lle.fit_transform(X[:100])
proj.shape

(100, 2)

Using $locally\_linear\_embedding$ to reconstruct the 2D data, which is mostly identical to above:

In [102]:
lle, _ = skl.manifold.locally_linear_embedding(X[:100], n_neighbors=5, n_components=2)
lle.shape

(100, 2)

**IsoMap**

Implementation of the IsoMap algorithm using Scikit-learn (page 302).

In [103]:
X = np.random.normal(size=(1000, 2))
R = np.random.random((2, 10))
X = np.dot(X, R)                # Now a 2D linear manifold in 10D space
X.shape

(1000, 10)

In [104]:
iso = skl.manifold.Isomap(n_neighbors=5, n_components=2)
proj = iso.fit_transform(X)
proj.shape

(1000, 2)

### 7.6. Independent Component Analysis

**ICA**

Implementation of ICA with Scikit-learn (page 305).

In [105]:
X = np.random.normal(size=(100, 2))
R = np.random.random((2, 5))
X = np.dot(X, R)            # Now 2D data in 5D space
X.shape

(100, 5)

Using $FastICA$ as in the book:

In [106]:
ica = skl.decomposition.FastICA(n_components=2)
proj = ica.fit_transform(X)
comp = ica.components_

**fit_transform** projects the data back into 2D space.

**Components** will return the components (here there are 2 with 5 features each).

In [107]:
print(f'Reconstructed data: {proj.shape} \nComponents: {comp}')

Reconstructed data: (100, 2) 
Components: [[ 0.81285387 -0.04997161 -0.22621649 -0.38630981  0.62967878]
 [ 1.19603666 -0.87930131 -0.97364203 -1.02524431  0.58270757]]


Using $fastica$ to reconstruct data:

In [109]:
_, _, proj = skl.decomposition.fastica(X, n_components=2)

proj.shape

(100, 2)