# Chapter 7 code blocks

In [110]:
import numpy as np
import scipy as sp
import sklearn as skl

np.random.seed(42)

### 7.3. Principal Component Analysis

**Single Value Decomposition (SVD) and Eigenvalue Decomposition (EVD)**

Checking that the diagonal matrix of eigenvalues $C_Y$ is equivalent to the square of the singular values ($\Sigma^2 = C_Y$), and the principal components can be computed from the SVD of $X$ without constructing $C_X$ (page 288).

In [111]:
X = np.random.random((100, 3))      # Initial dataset with 100 observations made up of 3 features each
CX = np.dot(X.T, X)                 # Covariance matrix of X

U, Sdiag, VT = np.linalg.svd(X, full_matrices=False)
        # U: left-singular vectors, VT: right-singular vectors, Sdiag: diagonal of singular values matrix
CYdiag, R = np.linalg.eigh(CX)
        # CYdiag: diagonal of the sqaure of the singular values, R: principal components

In [112]:
np.allclose(CYdiag, Sdiag[::-1]**2)     # Reverse Sdiag array

True

In [113]:
VT[::-1].T / R

array([[ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.]])

$C_Y$ and $\Sigma^2$ are equivalent; the right-hand vectors of $X$ (VT) and the eigenvectors of $C_X$ (R) are equivalent, disregarding the signs.

Using SciPy instead gives the same results:

In [114]:
U, Sdiag, VT = sp.linalg.svd(X, full_matrices=False)
CYdiag, R = sp.linalg.eigh(CX)

np.allclose(CYdiag, Sdiag[::-1]**2)     # Reverse Sdiag array

True

In [115]:
VT[::-1].T / R

array([[-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.]])

**Application of Principal Component Analysis**

Performing PCA using Scikit-learn (page 289).

In [116]:
X = np.random.normal(size=(100, 3))
R = np.random.random((3, 10))       # Projection matrix
X = np.dot(X, R)                    # Projecting X to 10D
X.shape

(100, 10)

In [117]:
pca = skl.decomposition.PCA(n_components=4)
comp = pca.fit_transform(X)             # Compute subspace projection of X to 4D
comp.shape

(100, 4)

*Mean* returns the mean value for each of the 10 features, to be used to centre the data vectors before analysis.

*Components* returns the eigenvectors of the prinical components (here there are 4 with 10 features each).

*Variance* returns the eigenvalues of the principal components (again 4, and the 4th is basically 0 because X originally had 3 dimensions).

In [118]:
mean = pca.mean_
components = pca.components_
var = pca.explained_variance_

print(f'Mean: {mean} \nComponents: {components} \nVariance: {var}')

Mean: [ 0.0097019   0.01275735  0.01538328  0.08679473  0.00701892  0.04095976
  0.04507729 -0.05242054  0.06871923 -0.00926229] 
Components: [[ 0.09762179  0.35593176  0.42233557  0.15652487  0.15427727  0.25357889
   0.19560691  0.50538303  0.23387673  0.47375002]
 [ 0.09930715 -0.1342657  -0.28645745  0.19131878  0.38925526 -0.48979933
  -0.38283823  0.15980508  0.52026703  0.13873163]
 [ 0.04705648  0.01551379  0.02299196  0.60037219  0.0079654   0.25479217
   0.29612294 -0.50603133  0.44211965 -0.17989114]
 [ 0.06119626 -0.24291535 -0.0865055   0.27784661 -0.16162277  0.03077087
   0.17800908  0.66293439  0.01177663 -0.5951374 ]] 
Variance: [9.28984050e+00 4.71388915e-01 2.78411978e-01 9.44661661e-16]


### 7.4. Nonnegative Matrix Factorisation

**NMF**

Implementing NMF with Scikit-learn (page 297).

In [119]:
X = np.random.random((100, 3))      # 100 points in 3D, all positive

nmf = skl.decomposition.NMF(n_components=3)
proj = nmf.fit_transform(X)         # Projecting to 3D
proj.shape

(100, 3)

*Components* will return the components (here there are 3).

*Reconstruction error* shows how well the components capture the original data.

In [120]:
comp = nmf.components_
err = nmf.reconstruction_err_

print(f'Components: {comp} \nError: {err}')

Components: [[3.32003111e+00 9.81286352e-02 0.00000000e+00]
 [3.77511306e-02 1.14796456e-03 1.92123142e+00]
 [0.00000000e+00 2.08622855e+00 4.00441721e-02]] 
Error: 0.007600229339938763


### 7.5. Manifold Learning

**Locally Linear Embedding**

Performing LLE with Scikit-learn (page 300).

In [121]:
X = np.random.normal(size=(1000, 2))
R = np.random.random((2, 10))
X = np.dot(X, R)                # Now a 2D linear manifold in 10D space
X.shape

(1000, 10)

Using $LocallyLinearEmbedding$ to reconstruct the original 2D data, as in the book:

In [122]:
lle = skl.manifold.LocallyLinearEmbedding(n_neighbors=5, n_components=2)
proj = lle.fit_transform(X[:100])
proj.shape

(100, 2)

Using $locally\_linear\_embedding$ to reconstruct the 2D data, which is mostly identical to above:

In [123]:
lle, _ = skl.manifold.locally_linear_embedding(X[:100], n_neighbors=5, n_components=2)
lle.shape

(100, 2)

**IsoMap**

Implementation of the IsoMap algorithm using Scikit-learn (page 302).

In [124]:
X = np.random.normal(size=(1000, 2))
R = np.random.random((2, 10))
X = np.dot(X, R)                # Now a 2D linear manifold in 10D space
X.shape

(1000, 10)

In [125]:
iso = skl.manifold.Isomap(n_neighbors=5, n_components=2)
proj = iso.fit_transform(X)
proj.shape

(1000, 2)

### 7.6. Independent Component Analysis

**ICA**

Implementation of ICA with Scikit-learn (page 305).

In [126]:
X = np.random.normal(size=(100, 2))
R = np.random.random((2, 5))
X = np.dot(X, R)            # Now 2D data in 5D space
X.shape

(100, 5)

Using $FastICA$ as in the book:

In [127]:
ica = skl.decomposition.FastICA(n_components=2)
proj = ica.fit_transform(X)
comp = ica.components_

**fit_transform** projects the data back into 2D space.

**Components** will return the components (here there are 2 with 5 features each).

In [128]:
print(f'Reconstructed data: {proj.shape} \nComponents: {comp}')

Reconstructed data: (100, 2) 
Components: [[-0.92431525  0.05042661 -0.1522238  -0.20568369 -0.14332723]
 [ 0.96380381 -2.22068748 -0.50808531 -0.45402968  0.24668916]]


Using $fastica$ to reconstruct data:

In [129]:
_, _, proj = skl.decomposition.fastica(X, n_components=2)

proj.shape

(100, 2)